# Cloud Build configuration for InSPyReNet Optimized API
# Builds optimized image without requiring local Docker

steps:
  # Step 1: Build the optimized Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/pet-bg-removal/inspirenet-bg-removal-api:critical-fix'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/pet-bg-removal/inspirenet-bg-removal-api:latest'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - '--cache-from'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/pet-bg-removal/inspirenet-bg-removal-api:gpu-optimized'
      - '--platform'
      - 'linux/amd64'
      - '.'
    timeout: '1200s'  # 20 minutes for build with optimizations

  # Step 2: Push both tags to registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/pet-bg-removal/inspirenet-bg-removal-api:critical-fix'
    
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/pet-bg-removal/inspirenet-bg-removal-api:latest'

  # Step 3: Deploy to Cloud Run using the clean production configuration
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'replace'
      - 'deploy-production-clean.yaml'
      - '--region=us-central1'
    timeout: '600s'  # 10 minutes for deployment

  # Step 4: Wait for deployment to be ready
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'wait'
      - 'inspirenet-bg-removal-api'
      - '--region=us-central1'
    timeout: '300s'

  # Step 5: Run health check to verify deployment
  - name: 'gcr.io/cloud-builders/curl'
    args:
      - '-f'
      - 'https://inspirenet-bg-removal-api-725543555429.us-central1.run.app/health'
    timeout: '60s'

  # Step 6: Trigger model preload warmup
  - name: 'gcr.io/cloud-builders/curl'
    args:
      - '-X'
      - 'POST'
      - 'https://inspirenet-bg-removal-api-725543555429.us-central1.run.app/warmup'
      - '--max-time'
      - '120'
    timeout: '180s'

options:
  # Use high-CPU machine for faster builds
  machineType: 'E2_HIGHCPU_8'
  
  # Enable build logs
  logging: CLOUD_LOGGING_ONLY


# Images to be pushed to registry
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/pet-bg-removal/inspirenet-bg-removal-api:critical-fix'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/pet-bg-removal/inspirenet-bg-removal-api:latest'

# Tags for build tracking
tags:
  - 'inspirenet-api'
  - 'gpu-optimized'
  - 'production-ready'

# Overall build timeout
timeout: '2400s'  # 40 minutes total 