apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gemini-artistic-api
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"  # CRITICAL: Scale to zero to save costs
        autoscaling.knative.dev/maxScale: "5"   # Max 5 concurrent instances
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 10  # 10 concurrent requests per instance
      timeoutSeconds: 300       # 5 minute timeout
      containers:
      - name: gemini-artistic-api
        image: us-central1-docker.pkg.dev/perkieprints-nanobanana/gemini-artistic/api:latest
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: "2000m"      # 2 CPU cores
            memory: "2Gi"     # 2GB RAM
        env:
        - name: GEMINI_API_KEY
          value: "AIzaSyAP6X8DdL1kPlah25du8s_YzipwOnYd_7I"
        - name: GEMINI_MODEL
          value: "gemini-2.5-flash-image"
        - name: PROJECT_ID
          value: "perkieprints-nanobanana"
        - name: PROJECT_NUMBER
          value: "753651513695"
        - name: STORAGE_BUCKET
          value: "perkieprints-processing-cache"
        - name: RATE_LIMIT_DAILY
          value: "5"
        - name: RATE_LIMIT_BURST
          value: "3"
        - name: DAILY_COST_CAP
          value: "10.0"
        - name: DEBUG
          value: "false"
